/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGSAP } from '@gsap/react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import gsap from 'gsap'
import { useRef } from 'react'
import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'

// generated with `--types` flag on
type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Ring: THREE.Mesh
    Sphere2: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

// PERF: group element is mapped to THREE.Group JSX element props
export default function Planet(props: ThreeElements['group']) {
  const shapeContainer = useRef<THREE.Group>(null)
  const shperesContainer = useRef<THREE.Group>(null)
  const ringMesh = useRef<THREE.Mesh>(null)

  const { nodes, materials } = useGLTF(
    '/models/planet.glb',
  ) as unknown as GLTFResult

  useGSAP(() => {
    const tl = gsap.timeline()

    // null check to satisfy typescript
    if (
      !shapeContainer.current ||
      !shperesContainer.current ||
      !ringMesh.current
    )
      return

    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: 'circ.out',
    })

    tl.from(
      shperesContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: 'power1.inOut',
      },
      '-=25%',
    )

    tl.from(
      ringMesh.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: 'power1.inOut',
      },
      '<',
    )
  }, [])

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials['Material.002']}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials['Material.001']}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringMesh}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials['Material.001']}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  )
}

useGLTF.preload('/models/Planet.glb')
